#!/usr/bin/env bash
# Replace [STUDENT_ID] with your actual student ID
STUDENT_ID="421731"

# Install HAProxy
sudo apt-get update
sudo apt-get install -y haproxy

# Configure HAProxy
sudo tee /etc/haproxy/haproxy.cfg > /dev/null <<EOL
global
    daemon
    maxconn 256

defaults
    mode http
    timeout connect 5000ms
    timeout client 50000ms
    timeout server 50000ms

frontend main
    bind *:80
    default_backend webservers

backend webservers
    balance roundrobin
    server $STUDENT_ID-web-01 52.3.247.21:80 check
    server $STUDENT_ID-web-02 34.207.237.255:80 check
EOL

# Restart HAProxy to apply changes
sudo service haproxy restart

# Enable HAProxy to be managed via init script
sudo systemctl enable haproxy

# Verify configuration
curl -Is 127.0.0.1

# Output success message
echo "HAProxy installed and configured successfully!"
