#!/usr/bin/env bash

# Double the number of webservers
sudo apt update
sudo apt install haproxy -y

# Set the student ID
student_id="421731"

# Configure HAProxy with the correct hostnames
webserver1="${student_id}-web-01"
webserver2="${student_id}-web-02"

sudo sh -c "echo -e \"\nlisten myserver\n\tbind *:80\n\tbalance roundrobin\n\tserver $webserver1 52.3.247.21:80 check\n\tserver $webserver2 34.207.237.255:80 check\n\" >> /etc/haproxy/haproxy.cfg"

sudo service haproxy restart
